- name: Create new user
  hosts: webservers
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Create a new user Johar
      ansible.builtin.user:
        state: present
        name: Johar
        group: www-data
        shell: /bin/bash