- hosts: webservers

  vars:
    root_dir: /home/denis/develop/ansible-education
    nginx_port: 80

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: "{{root_dir}}/files/nginx.conf"
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: update html
      ansible.builtin.copy:
        src: "{{root_dir}}/files/index2.html"
        dest: /usr/share/nginx/html/index.html
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
